#
# Docker compose file for TANGO database and database device server
#
# Defines:
#   - tangodb: MariaDB database with TANGO schema
#   - databaseds: TANGO database device server
#
# Requires:
#   - None
#
version: '2'
volumes:
  tangodb: {}

services:
  tangodb:
    image: nexus.engageska-portugal.pt/ska-docker/tango-db:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
    volumes:
      - tangodb:/var/lib/mysql

  databaseds:
    image: nexus.engageska-portugal.pt/ska-docker/tango-databaseds:latest
    depends_on:
      - tangodb
    environment:
      - MYSQL_HOST=tangodb:3306
      - MYSQL_DATABASE=tango
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - TANGO_HOST=databaseds:10000
    entrypoint:
      - /usr/local/bin/wait-for-it.sh
      - tangodb:3306
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/DataBaseds
      - "2"
      - -ORBendPoint
      - giop:tcp::10000

  dsconfig:
    image: nexus.engageska-portugal.pt/ska-docker/tango-dsconfig:1.5.0
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=databaseds:10000
    command: json2tango tangodb/config.json -w
    volumes:
      - /home/phelokazi/k/tango-example:/tangodb
  
  calenderclock:
    image: artefact.skao.int/ska-tango-examples:0.4.15
    depends_on:
      - dsconfig
    environment:
      - TANGO_HOST=databaseds:10000
    command: sleep infinity
  
  eventreceiver:
    image: artefact.skao.int/ska-tango-examples:0.4.15
    depends_on:
      - dsconfig
    environment:
      - TANGO_HOST=databaseds:10000
    command: python /app/src/ska_tango_examples/basic_example/EventReceiver.py test
  
  motor:
    image: artefact.skao.int/ska-tango-examples:0.4.15
    depends_on:
      - dsconfig
    environment:
      - TANGO_HOST=databaseds:10000
    command:  python /app/src/ska_tango_examples/basic_example/Motor.py test
     

