display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: ska-tango-examples
telescope: SKA-mid

labels:
  app: tango-example

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  databaseds_port: 10000
  device_server_port: 45450
  retry:
  - "--tries=10"
  - "--sleep=5"
  DEBUG: 5678

dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.3
    pullPolicy: IfNotPresent

tango_example:
  image:
    registry: artefact.skao.int
    image: ska-tango-examples
    tag: 0.4.15
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

deviceServers:
  powersupply:
    instances: ["test"]
    file: "data/powersupply.yaml"
  motor:
    instances: ["test"]
    file: "data/motor.yaml"
  eventreceiver:
    instances: ["01"]
    file: "data/eventreceiver.yaml"
  calendarclock:
    instances: ["test"]
    file: "data/calendarclock.yaml"


nodeSelector: {}

tolerations: []

affinity: {}

